FROM arm64v8/node:20-alpine

WORKDIR /app

COPY package.json .
COPY tsconfig.json .
COPY .npmrc .
COPY src ./src

RUN ls -a
RUN npm install
RUN npm i -g nodemon

EXPOSE 4003

CMD [ "npm", "run", "dev" ]
